### PR TITLE
[wip] build MPI variants

### PR DESCRIPTION
**Pull request by minrk**
Implement [this proposal](https://github.com/conda-forge/staged-recipes/pull/1501#issuecomment-280660604) for MPI variants.

Probably shouldn't be merged before a decision is reached there.

Won't work until upstream PRs tracking features are merged:

- https://github.com/conda-forge/mpich-feedstock/pull/11
- https://github.com/conda-forge/openmpi-feedstock/pull/11

### CODE REVIEW

**Comment by guillochon** [comment]
What's the status on this? The `mpich` conda install appears to mess with `O_NONBLOCK` flag which screws with the terminal on OS X/Linux, and thus it seems preferable to install `mpi4py` using `openmpi` rather than `mpich`.

**Comment by minrk** [comment]
This needs to wait for a resolution to https://github.com/conda-forge/staged-recipes/pull/1501 before it can proceed.

FWIW, the mpich ticket for this appears to be [this one](http://trac.mpich.org/projects/mpich/ticket/1782) with no apparent resolution or workaround.

**Comment by pkgw** [comment]
I have been helping @guillochon track down the `mpich` problem and I think I have a better understanding of the cause. It seems to only be triggered when using Bash version 4 on OS X — but only because other versions of bash turn the `O_NONBLOCK` flag off as soon as they print the prompt after any programs run (essentially; [code here](http://git.savannah.gnu.org/cgit/readline.git/tree/shell.c#n191)). All versions of `mpich` do have a thing where they turn the `O_NONBLOCK` flag on the user's TTY, which I am pretty sure is no-no behavior. Bash just hides it in most cases.

Anyway, I have been trying to convey this information to the `mpich` developers, and it is *extremely* hard for me to figure out how to even get in touch with them or add a comment on their bug tracker. This sort of thing makes me tend to think that OpenMPI might be the more preferable implementation.

**Comment by dalcinl** [comment]
@pkgw MPICH developers can be contacted though their mailing list `devel@mpich.org`. 

I've been developing mpi4py using MPICH and Open MPI since 2004. In 13 years of using MPICH, I never had any serious issue with it I found just a few of minor bugs. In the case of Open MPI, well, they have a tradition of breaking mpi4py testsuite release after release, just look for my name in Open MPI mailing list and you will notice how many bugs I reported over the years. Also, look at mpi4py's testsuite and look how many tests I had to disable for different Open MPI releases to get the whole test run pass.

So, if my previous experience is of any value to anyone, I would recommend keeping MPICH the default MPI implementation, and work out with MPICH devs any issue we encounter, or eventually patch MPICH to fix the `O_NOBLOCK` issue to fit our needs. This recommendation is not based on my personal preferences, it is just a mater of offering to end users a default choice that can be trusted upgrade after upgrade. 

Of course, @minrk is leading the effort (with much more patience and hard work than me) to get a robust MPI infrastructure in conda-forge, so the final decision is on him and I will not hesitate to unconditionally support it.

**Comment by pkgw** [comment]
@dalcinl OK, clearly your experience is much more relevant than my superficial interactions! But while we're here ... assuming you have an account on their Trac system, could you please add a comment to their [ticket 1782](http://trac.mpich.org/projects/mpich/ticket/1782) relaying the following information?

> My colleagues and I have run into the problem reported in the bug and have traced it down a bit. Mpich does indeed seem to have a bug where it sets the `O_NONBLOCK` flag on the processes' stdout/stderr file descriptors in common modes. This bug does not generally surface, however, because bash has code that turns the flags *off* after each command that it runs (if needed, as signaled by it getting `EAGAIN` when doing I/O to the TTY).
> 
> The code that's directly responsible is in `alloc_fwd_hash` in `src/pm/hydra/utils/sock.sock.c`. It's triggered by code in places like `src/pm/hydra/tools/bootstrap/external/external_common_launch.c : HYDT_bscd_common_launch_procs()`, where there is some demuxer registration step that involves the callback `HYDT_bscu_stdio_cb` that eventually calls the `alloc_fwd_hash` function. I do not know enough about mpich to understand which piece is at fault, but I do believe that it is inappropriate for mpich to set TTY file descriptors to nonblocking mode. Interestingly, it seems that the descriptors have their nonblocking mode set only at the *end* of the execution of programs like `mpirun`.
> 
> You can trigger this bug on OS X by using the Homebrew version of bash 4.4, which, for reasons not entirely clear to me, does not run the bit of code that clears the O_NONBLOCK flags. The default bash on OSX, version 3, does, and so the problem doesn't surface when you use that shell.

I have to admit that I can't be bothered to sign up for the mailing list to send a message to it to request an account on the Trac so that I can add a comment on the bug.

**Comment by minrk** [comment]
I don't have preferences for mpich vs openmpi as default, but I trust @dalcinl's experience maintaining mp4py. mpich is mainly the default because it got into the conda-forge pipeline first so it propagated through other packages while there continues to be no mechanism for variants. We still need to wait for conda-forge/staged-recipes#1501 before we can proceed with adding an openmpi variant, though (switching mpi4py to depend on openmpi before propagating the variants would make a big mess).

**Comment by dalcinl** [comment]
@pkgw MPICH development repo is not on GitHub https://github.com/pmodels/mpich/issues

**Comment by minrk** [comment]
The O_NONBLOCK issue appears to be [fixed](https://github.com/pmodels/mpich/pull/2755) in mpich [3.2.1](https://github.com/conda-forge/mpich-feedstock/pull/19)

**Pull request closed without merging**
