### PR TITLE
Compile for latest openmpi version

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
When I try to rerender locally I get the following error:
```
INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2021.01.14.19.12.27
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /var/folders/z7/3vhrmssx60v240x_ndq448h80000gn/T/tmp8hxa1ucu
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /var/folders/z7/3vhrmssx60v240x_ndq448h80000gn/T/tmp8hxa1ucu/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /var/folders/z7/3vhrmssx60v240x_ndq448h80000gn/T/tmp8hxa1ucu/conda_build_config.yaml
Adding in variants from /Users/jan/Desktop/mpi4py-feedstock/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /Users/jan/Desktop/mpi4py-feedstock/recipe/conda_build_config.yaml
INFO:conda_smithy.configure_feedstock:Applying migrations: /var/folders/z7/3vhrmssx60v240x_ndq448h80000gn/T/tmp8hxa1ucu/share/conda-forge/migrations/pypy.yaml,/var/folders/z7/3vhrmssx60v240x_ndq448h80000gn/T/tmp8hxa1ucu/share/conda-forge/migrations/python39.yaml
Adding in variants from argument_variants
INFO:conda_build.variants:Adding in variants from argument_variants
```

**Review by leofang — CHANGES_REQUESTED** [review]
I don't think this is necessary. Open MPI has backward compatibility in its ABI (which I just learned yesterday: https://github.com/conda-forge/openmpi-feedstock/issues/74#issuecomment-759753071).

**Comment by jan-janssen** [comment]
The issue is not the API but the pinning from conda as demonstrated in https://github.com/conda-forge/mpi4py-feedstock/issues/36

**Comment by jan-janssen** [comment]
Drone issue:
```
Total disk usage observed (not including envs): 12.0K
937	+ validate_recipe_outputs mpi4py-feedstock
938	Cloning into '/tmp/tmpkymmvvjd_recipe/feedstock-outputs'...
939	fatal: unable to access 'https://github.com/conda-forge/feedstock-outputs.git/': OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443 
```

**Comment by jan-janssen** [comment]
@conda-forge-admin, please restart ci

**Comment by leofang** [comment]
@jan-janssen Thank you. A conflict happens because we relaxed Open MPI's pinning yesterday. However, this isn't a proper fix, as the fix must be done for all downstream feedstocks, not just mpi4py. I will try to work out a patch tonight (on my cell & outside now) as suggested by @isuruf, but if you'd like to give it a shot, feel free to follow https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1106#issuecomment-759806233 and send a PR to patch the repodata.

**Pull request closed without merging**
