### PR TITLE
MNT: rerender

### LINKED ISSUE #51: @conda-forge-admin rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #51.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #51

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by dalcinl** [comment]
@beckermr Should I merge?

**Comment by beckermr** [comment]
No not yet. There is a bug in smithy I need to fix first. Thanks for checking in!

**Comment by beckermr** [comment]
This PR can be closed.

**Pull request closed without merging**
