### PR TITLE
Rebuild for MS-MPI

### PR DESCRIPTION
**Pull request by leofang**
The previous MS-MPI releases had an issue in `MSMPI_VER`, which is fixed in conda-forge/msmpi-feedstock#6. It requires a rebuild of mpi4py to take advantage of it. 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@dalcinl Continuing our discussion in https://github.com/mpi4py/mpi4py/issues/19#issuecomment-826464128, I still think we need a patch for mpi4py to handle `MSMPI_VER`:
```
building 'mpi4py.MPI' extension
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DMSMPI_VER=0x701 -ID:\bld\mpi4py_1619410547854\_h_env\include -ID:\bld\mpi4py_1619410547854\_h_env\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -ID:\bld\mpi4py_1619410547854\_h_env\Library\include -ID:\bld\mpi4py_1619410547854\_h_env\Library\include -ID:\bld\mpi4py_1619410547854\_h_en...
  MPI.c
  D:\bld\mpi4py_1619410547854\_h_env\Library\include\mpi.h(75): warning C4005: 'MSMPI_VER': macro redefinition
  src/MPI.c: note: see previous definition of 'MSMPI_VER'
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=308858&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=664
The `-DMSMPI_VER=0x701` flag is taken from the Windows Registry for the existing MPI installation in the image, which mismatches Conda's version.

**Comment by dalcinl** [comment]
This is just a warning. The mpi4py build is still correct

> I still think we need a patch for mpi4py to handle `MSMPI_VER`:

Yes, of course. However, there is no actual need of patching the mpi4py recipe at this point, unless you really want to silence the warning from the build logs. Any fix could go directly to mpi4py/master.

PS: Please download the msmpi conda package and look at mpi.h, in the place where you `#define MSMPI_VER`. You will notice bad line endings in all the stuff you added to the file. More exactly, you added LF line terminators, while the all the include files use CRLF line terminators. I'm not sure what's the proper way to "fix" this in the msmpi recipe.

Also, you should remove the trailing comments in the `#define MSMPI_VER`. I should have noticed this issue earlier, sorry. Perhaps is not really important for the MSVC compiler and its preprocessor, but as I do not know whether the default preprocessor (or other user-invoked non-default preprocessor) removes or not trailing comments, so I prefer to not play with fire.

**Comment by leofang** [comment]
> This is just a warning. The mpi4py build is still correct
> 
> > I still think we need a patch for mpi4py to handle `MSMPI_VER`:
> 
> Yes, of course. However, there is no actual need of patching the mpi4py recipe at this point, unless you really want to silence the warning from the build logs. Any fix could go directly to mpi4py/master.

OK I was worried that the warning may be accompanied by something incorrect. Should I check the return value more explicitly? Say, `assert MPI.Get_vendor[1] == (10, 1, 0)`?

Re: line ending and tailing comment: Good catch @dalcinl! I sent a PR to fix it: https://github.com/conda-forge/msmpi-feedstock/pull/9.

**Comment by leofang** [comment]
(Though I wonder why line ending is an issue...I thought the patcher would fix it automatically.)

**Comment by dalcinl** [comment]
> Should I check the return value more explicitly?

I would say no, it is not worth it. We will eventually push a fix to mpi4py/master to special case conda-build, and at that point the warning will be gone.

**Comment by dalcinl** [comment]
> Though I wonder why line ending is an issue...

Because other windows tools may expect text files to have CRLF line endings? So we should follow the rules to prevent any potential issue. I'm not a windows expert. When I do know something well, I try to stay as close as possible to defaults.

**Comment by leofang** [comment]
@conda-forge-admin, please restart ci

**Comment by leofang** [comment]
> I sent a PR to fix it: conda-forge/msmpi-feedstock#9.

This was in and is being picked up by the CI. I think we're good.

**Pull request merged**
