### PR TITLE
Update 3.0.1

### PR DESCRIPTION
**Pull request by dalcinl**
Update to mpi4py 3.0.1

### CODE REVIEW

**Comment by dalcinl** [comment]
@minrk Should I set the build number to `1000` as I did in this PR, or should I use `0` ?

**Comment by minrk** [comment]
it can bump back down to 0 if it's a new version

**Comment by dalcinl** [comment]
@minrk OK to merge? The failure in Azure is most likely not mpi4py's fault...

**Comment by minrk** [comment]
Yeah, safe to ignore the new azure builds for now

**Pull request merged**
