### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #26.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by ax3l** [comment]
@minrk didn't you find a work-around for https://github.com/conda/conda-build/issues/3799 by downloading a `.tar` instead or so?

**Comment by minrk** [comment]
@ax3l I just used the checksum of the .tar after unzipping the .tar.gz in the meta.yaml. I guess that counts as a workaround? I didn't think to try asking bitbucket for a .tar file.

**Comment by ax3l** [comment]
Yes, it's not yet fixed upstream. We might have to use that work-around for now, do you want to apply it to `mpi4py`?

**Comment by dalcinl** [comment]
@ax3l I'm not sure asking for a `.tar` file would work. These tarballs are release tarballs that I manually upload, they are not autogenerated ouf of the git repository.

**Pull request merged**
