### PR TITLE
recipe: Add patch to fix mpi.pth issues in Python 3.13

### PR DESCRIPTION
**Pull request by dalcinl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dalcinl** [comment]
@minrk This `mpi.pth` file I'm patching is not strictly needed if mpi4py is installed in a conda environment alongside the MSMPI or the Intel MPI packages also installed in the environment. Maybe this PR should instead remove the file after installation?

**Comment by minrk** [comment]
I think removing the file is fine, but so is keeping the patch, if you prefer. This .pth behavior seems unlikely to have a _positive_ effect in a conda env, if/when it has an effect at all, since dependencies are bundled appropriately in conda.

**Comment by dalcinl** [comment]
OK, let's keep it for now then, just to not change things respect to previous builds of this release. 
Off topic: if you have any better approach to suggest to deal with Windows DLL paths for non-conda envs, please share.

**Comment by minrk** [comment]
>  if you have any better approach to suggest to deal with Windows DLL paths for non-conda envs, please share.

I wish I did! It's been a huge pain, and I don't understand it well.

But it does seem like you should be able to do this in `__init__.py` without the .pth file, as long as it runs before you import the extension.

[delvewheel](https://github.com/adang1345/delvewheel) is the DLL-bundling tool for Windows wheels (I assume MS/intel mpi DLLs don't allow redistribution), but the way it works is [injecting a call to os.add_dll_directory](https://github.com/adang1345/delvewheel/blob/bafa435c8cbd13cb87f86901bc54659903357d0f/delvewheel/_wheel_repair.py#L64) to `__init__.py` before anything else.

I can't speak to whether there's better logic than your use of env vars, but it should at least be safe to put it in a regular Python file, rather than relying on `.pth` behaviors.

**Comment by minrk** [comment]
That makes sense! I've faced exactly that kind of thing in fenics with the import order of mpi4py, petsc4py, and dolfinx, so I get it.

You should still be able to move it to a _dedicated_ .py file by switching your .pth to a one-liner that imports your 'real' module to do the work. This is what editable installs look like with pip now:

```python
import __editable___jupyterhub_4_1_5_finder; __editable___jupyterhub_4_1_5_finder.install()
```

and it installed a module `__editable___jupyterhub_4_1_5_finder.py` with the actual import-from-somewhere logic.

You could follow suit with an `_mpi4py_find_dll.py` that has this logic, and make your .pth a one-liner:

```python
import _mpi4py_find_dll; _mpi4py_find_dll.find_dlls()
```

**Comment by dalcinl** [comment]
OK, makes sense. I'll try soon to clean up this mess following your advice. I'll mention you in the corresponding mpi4py PR. Thanks.

**Pull request merged**
